/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test.check" instead.
 */

#include <check.h>

#line 1 "test.check"
#include "calculate.h"
#include <math.h>

double EPS = 0.0000001;


START_TEST(Calculation_test_1) {
#line 24

char *str4 = "123-sin(4)*log(13)-cos(15+225)/ln(78)";
double a = 123.76825818;
double b = calc(str4, 0);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_2) {
#line 33

char *str5 = "sqrt(5+(atan(-5+3)))*6^2";
double a = 71.02911559;
double b = calc(str5, 0);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_3) {
#line 42

char *str6 = "asin(0.3)-acos(0.3)*tan(0.3/atan(0.3))";
double a = -1.8003964;
double b = calc(str6, 0);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_4) {
#line 51

char *str7 = "tan(acos(0.166231))/sin(log(atan(0.166231)))+cos(sqrt(2.12321-0.166231))";
double a = -8.23627725901;
double b = calc(str7, 0);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_5) {
#line 51

char *str7 = "sqrt(5+(atan(-5+3)))*6^2+5mod2";
double a = 71.02911559;
double b = calc(str7, 0);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_6) {
#line 51

char *str7 = "2+x";
double a = 4;
double b = calc(str7, 2);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_7) {
#line 51

char *str7 = "1565146modx";
double a = 392;
double b = calc(str7, 542);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_8) {
#line 51

char *str7 = "1565146modx*tan(0.7)/5+1";
double a = 67.035409027;
double b = calc(str7, 542);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_9) {
#line 51

double amount_credit = 120000;
double time_credit = 15;
double percent_credit = 8;
double mouth_pay = 0;
double percent = 0;
double all = 0;
credit_calculate(amount_credit, percent_credit, time_credit, &mouth_pay, &percent, &all);
ck_assert_double_ne(mouth_pay, 8433.28);
ck_assert_double_ne(percent, 6499.21);
ck_assert_double_ne(all, 126499);
}
END_TEST


START_TEST(Calculation_test_10) {
#line 51

char *str7 = "cos(sin(8)+ln(8))";
double a = -0.99735176906;
double b = calc(str7, 0);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_11) {
#line 51

char *str7 = "v";
double a = 0;
double b = calc(str7, 0);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_12) {
#line 51

char *str7 = "cot";
double a = 0;
double b = calc(str7, 0);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_13) {
#line 51

char *str7 = "5.";
double a = 0;
double b = calc(str7, 0);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_14) {
#line 51

char *str7 = ".5";
double a = 0;
double b = calc(str7, 0);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_15) {
#line 51

char *str7 = "5/0";
double a = 0;
double b = calc(str7, 0);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_16) {
#line 51

char *str7 = "5+";
double a = 0;
double b = calc(str7, 0);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_17) {
#line 51

char *str7 = "+5";
double a = 0;
double b = calc(str7, 0);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_18) {
#line 51

char *str7 = "f+5";
double a = 0;
double b = calc(str7, 0);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_19) {
#line 51

char *str7 = "5+f";
double a = 0;
double b = calc(str7, 0);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_20) {
#line 51

char *str7 = "5mid2";
double a = 0;
double b = calc(str7, 0);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_21) {
#line 51

char *str7 = "5mof2";
double a = 0;
double b = calc(str7, 0);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_22) {
#line 51

char *str7 = "5pod2";
double a = 0;
double b = calc(str7, 0);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_23) {
#line 51

char *str7 = "5*4/2-6/7+45";
double a = 54.1428571429;
double b = calc(str7, 0);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_24) {
#line 51

char *str7 = "5+(2*3+6/3-3*2/1)";
double a = 7;
double b = calc(str7, 0);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_25) {
#line 51

char *str7 = "5+2-1*3/2+(2*1/3*2+(4/2*3+1))";
double a = 13.8333333333;
double b = calc(str7, 0);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_26) {
#line 51

char *str7 = "5+2-1*3/2+(2*1/3*2+(4/2*3+1-(4/5*2/1+2)))";
double a = 10.2333333333;
double b = calc(str7, 0);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_27) {
#line 51

char *str7 = "5+2-1*3/2+(2*1/3*2+(4/2*3+1-(4/5*2/1+2-(55+11/2))))";
double a = 70.7333333333;
double b = calc(str7, 0);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_28) {
#line 51

char *str7 = "5+(cos(2/4)+(0,5-0,1+(1*2-(2*5))))";
double a =  -1.72241743811;
double b = calc(str7, 0);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

START_TEST(Calculation_test_29) {
#line 51

char *str7 = "5+(cos(2/4)+(sin(0.3+cos(3.14))-0.1+(1*2-(2*5))))";
double a =  -2.86663415532;
double b = calc(str7, 0);
double res = a - b;
ck_assert_double_lt(res, EPS);
}
END_TEST

int main(void) {
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, Calculation_test_1);
    tcase_add_test(tc1_1, Calculation_test_2);
    tcase_add_test(tc1_1, Calculation_test_3);
    tcase_add_test(tc1_1, Calculation_test_4);
    tcase_add_test(tc1_1, Calculation_test_5);
    tcase_add_test(tc1_1, Calculation_test_6);
    tcase_add_test(tc1_1, Calculation_test_7);
    tcase_add_test(tc1_1, Calculation_test_8);
    tcase_add_test(tc1_1, Calculation_test_9);
    tcase_add_test(tc1_1, Calculation_test_10);
    tcase_add_test(tc1_1, Calculation_test_11);
    tcase_add_test(tc1_1, Calculation_test_12);
    tcase_add_test(tc1_1, Calculation_test_13);
    tcase_add_test(tc1_1, Calculation_test_14);
    tcase_add_test(tc1_1, Calculation_test_15);
    tcase_add_test(tc1_1, Calculation_test_16);
    tcase_add_test(tc1_1, Calculation_test_17);
    tcase_add_test(tc1_1, Calculation_test_18);
    tcase_add_test(tc1_1, Calculation_test_19);
    tcase_add_test(tc1_1, Calculation_test_20);
    tcase_add_test(tc1_1, Calculation_test_21);
    tcase_add_test(tc1_1, Calculation_test_22);
    tcase_add_test(tc1_1, Calculation_test_23);
    tcase_add_test(tc1_1, Calculation_test_24);
    tcase_add_test(tc1_1, Calculation_test_25);
    tcase_add_test(tc1_1, Calculation_test_26);
    tcase_add_test(tc1_1, Calculation_test_27);
    tcase_add_test(tc1_1, Calculation_test_28);
    tcase_add_test(tc1_1, Calculation_test_29);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
